kumuluzee:
  name: users-service-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    annotations:
      users-resource:
        allow-origin: "*"
        allow-subdomains: true
        supported-methods: "GET, POST, DELETE, HEAD, OPTIONS, PUT"
